local opt = vim.opt
opt.arabicshape = true -- Correctly displays Arabic characters' shapes.
opt.autoindent = true -- Copies the indentation from the previous line when starting a new line.
opt.autoread = true -- Automatically reloads a file if it was changed outside of Neovim
opt.autowrite = false -- Automatically writes changes to a file when switching buffers or exiting Neovim
opt.breakindent = true -- Indents wrapped lines to match code indentation
opt.clipboard = "unnamedplus" -- Uses the system clipboard (+) for all copy/paste operations.
opt.cmdheight = 0 -- Hides the command line area (set to 0 lines).
opt.colorcolumn = "+1" -- Draw column on the right of maximum width
opt.completeopt = "menuone,noselect,fuzzy,nosort" -- Configures the autocompletion popup
opt.copyindent = true -- When auto-indenting, copies the indentation structure from the previous line.
opt.cursorline = true -- Highlights the entire line your cursor is currently on.
opt.diffopt:append("algorithm:patience") -- Uses the "patience" algorithm for better diffs
opt.diffopt:append("linematch:60") -- Improves diff algorithm for better diffs
opt.diffopt:append("vertical") -- Opens diffs in vertical splits
opt.errorbells = false -- remove all errors
opt.expandtab = true -- Converts all <Tab> key presses into spaces.
opt.fillchars = {
	eob = " ",
	fold = " ",
	foldclose = "",
	foldopen = "",
	foldsep = " ",
	foldinner = " ",
	msgsep = "─",
}
opt.foldlevel = 0 -- Fold nothing by default; set to 0 or 1 to fold
opt.foldmethod = "marker" -- Fold based on marker level
opt.foldnestmax = 10 -- Limit number of fold levels
opt.foldtext = "" -- Show text under fold with its highlighting
opt.formatlistpat = [[^\s*[0-9\-\+\*]\+[\.\)]*\s\+]]
opt.formatoptions = "rqnl1j" -- Controls various automatic formatting options (e.g., 'c' wraps comments).
opt.hlsearch = true -- Automatically highlights all matches for your last search.
opt.ignorecase = true -- Makes all searches case-insensitive.
opt.inccommand = "split" -- Shows a live preview of a substitute-command (`:s/.../.../`) in a split window.
opt.incsearch = true -- Shows search matches as you type (incremental search).
opt.infercase = true -- Infer case in built-in completion
opt.iskeyword = "@,48-57,192-255,-" -- Treats hyphenated words as a single word for motions and text objects
opt.laststatus = 3 -- Sets the status line to be *always* visible (global status line).
opt.linebreak = true -- Wrap lines at 'breakat' (if 'wrap' is set)
opt.listchars = { tab = " ↦", trail = "·", nbsp = "␣" } -- Defines characters for invisible items
opt.list = true -- Enables the display of invisible characters.
opt.mouse = "a" -- Enables mouse support in all modes (clicking, scrolling, resizing splits).
opt.number = true -- Shows absolute line numbers for every line.
opt.numberwidth = 2 -- Sets the width of the line number column to 2 characters.
opt.pumborder = "bold" -- Adds a border to the completion popup menu. {"bold", "rounded", "single", "double"}
opt.pumheight = 15 -- Limits the height of the completion popup menu to 10 items.
opt.pummaxwidth = 80 -- Limits the width of the completion popup.
opt.relativenumber = true -- Shows line numbers relative to the cursor (e.g., 1, 2, 3... away).
opt.ruler = false -- Hides the cursor position (row/col) from the bottom-right corner.
opt.scrolloff = 8 -- Keeps 8 lines of context visible above and below the cursor when scrolling.
opt.shiftwidth = 2 -- Sets the width for indentation operations (like >> or <<) to 2 spaces.
opt.shortmess = "loOstTWAcF" -- Shortens the messages Vim displays (e.g., I: hiding the intro message).
opt.showbreak = "↪ " -- string to put at the start of wrapped lines
opt.showcmdloc = "statusline" -- Shows pending commands in the status line instead of the (hidden) command line.
opt.showmatch = true -- show matching parenthesis with a quick jump
opt.showmode = false -- Disables the mode indicator (e.g., -- INSERT --) at the bottom.
opt.signcolumn = "yes" -- Always displays the "sign column" on the left (used for diagnostics, Git signs, etc.).
opt.smartcase = true -- Overrides 'ignorecase' if your search term contains an uppercase letter.
opt.smartindent = true -- Enables "smart" indentation (e.g., automatically indenting after '{' in C-like files).
opt.smoothscroll = true -- Makes scrolling smoother
opt.softtabstop = 2 -- Makes the <Tab> key insert 2 spaces (works with `expandtab`).
opt.spelloptions = "camel" -- Treat camelCase word parts as separate words
opt.splitbelow = true -- Makes new horizontal splits (e.g., :split) open *below* the current window.
opt.splitkeep = "screen" -- Reduce scroll during window split
opt.splitright = true -- Makes new vertical splits (e.g., :vsplit) open to the *right* of the current window.
opt.tabstop = 2 -- Sets the visual width of a <Tab> character to 2 spaces.
opt.termguicolors = true -- Enables 24-bit "true color" support (requires a compatible terminal).
opt.timeoutlen = 300 -- Reduces the time Vim waits for you to complete a mapping (e.g., 'gd').
opt.title = true -- Sets the terminal window title to the current file name.
opt.ttimeoutlen = 10 -- Reduces the time Vim waits for an ambiguous terminal key code.
opt.undofile = true -- Saves undo history to a file, allowing you to undo *after* closing and reopening a file.
opt.updatetime = 300 -- Reduces the time of inactivity before writing swap files and triggering CursorHold events.
opt.virtualedit = "block" -- Allow cursor to move where there is no text in visual block mode
opt.wildmenu = true -- Enables an enhanced completion menu when typing commands or paths.
opt.wildmode = "longest:full,full"
opt.wrap = false -- Disables automatic line wrapping; long lines will scroll horizontally.
