$primary = rgb(990000)
$surface = rgb(121212)
$secondary = rgb(8c8c8c)
$error = rgb(d64646)
$tertiary = rgb(b3b3b3)
$surface_lowest = rgb(141414)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
