#!/usr/bin/env bash
set -euo pipefail

MENU_ITEMS=(
  "Blur|blur"
  "Decoration|decoration"
  "Fullscreen|fullscreen"
  "Master|master"
  "Dwindle|dwindle"
  "Scrolling|scrolling"
  "Monocle|monocle"
  "Opacity 1.0|opacity_10"
  "Opacity 0.95|opacity_9"
  "Opacity 0.1|opacity_1"
)

blur() {
  hyprctl dispatch setprop active no_blur toggle
}

decoration() {
  hyprctl dispatch setprop active decorate toggle
}

fullscreen() {
  classes=$(hyprctl clients -j | jq -r '.[].class' | sort -u)
  selected_class=$(echo "$classes" | bmenu -p "Select Class:")

  if [ -z "$selected_class" ]; then
    return
  fi

  hyprctl dispatch focuswindow "class:^(${selected_class})$"
  hyprctl dispatch fullscreen 0
}

master() {
  hyprctl keyword general:layout master
}

dwindle() {
  hyprctl keyword general:layout dwindle
}

scrolling() {
  hyprctl keyword general:layout scrolling
}

monocle() {
  hyprctl keyword general:layout monocle
}

opacity_10() {
  hyprctl dispatch setprop active opacity 1
}
opacity_9() {
  hyprctl dispatch setprop active opacity 0.95
}
opacity_1() {
  hyprctl dispatch setprop active opacity 0.1
}

CHOICE=$(for item in "${MENU_ITEMS[@]}"; do
  IFS="|" read -r label _ <<<"$item"
  echo "$label"
done | bmenu "Rules")

for item in "${MENU_ITEMS[@]}"; do
  IFS="|" read -r label func <<<"$item"
  if [[ "$CHOICE" == "$label" ]]; then
    "$func"
    exit 0
  fi
done

exit 1
