#!/usr/bin/env bash
set -euo pipefail

project_dir=~/Documents/Projects/

list() {
  selected=$(ls -t ~/Documents/Projects/ | bmenu "Project")
  [[ -n "$selected" ]] && foot nvim $project_dir/$selected
}

list
