#!/usr/bin/env bash

# Check the current status of Bluetooth
BLUETOOTH_STATUS=$(rfkill list bluetooth | grep -i 'Soft blocked: yes')

if [ -z "$BLUETOOTH_STATUS" ]; then
  rfkill block bluetooth
  notify-send "󰂲 Bluetooth off"
else
  rfkill unblock bluetooth
  notify-send "󰂯 Bluetooth on"
fi
