#!/usr/bin/env bash

# Kill already running processes
_ps=(.quickshell-wra)
for _prs in "${_ps[@]}"; do
    pkill "${_prs}"
done

sleep 1

#Relunch
noctalia-shell &

#Refresh hyprland
hyprctl reload
hyprctl dispacth forcerendererreload


exit 0
