#!/usr/bin/env bash

# Kill already running processes
_ps=(.quickshell-wra rofi)
for _prs in "${_ps[@]}"; do
  if pidof "${_prs}" >/dev/null; then
    pkill "${_prs}"
  fi
done

sleep 0.3

#Refresh hyprland

hyprctl reload
hyprctl dispacth forcerendererreload

#Relunch

noctalia-shell &

exit 0
