#!/usr/bin/env bash

# env
file=/tmp/vimwere
id="float_vim_capture"

# window rules
hyprctl keyword windowrule "match:class ${id},float 1" >/dev/null
hyprctl keyword windowrule "match:class ${id},size 1000 500" >/dev/null
hyprctl keyword windowrule "match:class ${id},move 500 60" >/dev/null

# window
foot --app-id="$id" nvim "$file"

if [[ -f "$file" ]]; then
  # copy
  wl-copy <"$file"
  # paste
  hyprctl dispatch sendkeystate "CTRL+SHIFT,v,down,activewindow"
  hyprctl dispatch sendkeystate "CTRL+SHIFT,v,up,activewindow"
  # clean
  rm "$file"
fi
