[class]
image_default	= [
	{ command = "nomacs", fork = true, silent = true },
	{ command = "gimp", fork = true, silent = true } ]

[extension]
# inherit from image_default class
png.inherit	= "image_default"

# inherit from image_default class
jpg.inherit	= "image_default"
# in addition, also add gimp for .jpg files only
jpg.app_list	= [
	{ command = "gimp", fork = true, silent = true } ]

mov.app_list	= [
	{ command = "vlc", fork = true, silent = true }]

mp4.app_list	= [
	{ command = "vlc", fork = true, silent = true }]

mkv.app_list	= [
	{ command = "vlc", fork = true, silent = true }]

rs.app_list	= [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]

pdf.app_list = [
  { command = "zathura",  fork = true }]

mp3.app_list = [
  { command = "mpv", fork = true, silent = true }]  

[mimetype]

# text/*
[mimetype.text]
inherit = "nvim"

# application/octet-stream
[mimetype.application.subtype.octet-stream]
inherit = "video_default"
