#!/bin/bash

WALLPAPER_DIR="$HOME/Pictures/wallpapers"
INTERVAL=1800 # 30 minutes in seconds
PREVIOUS_WALLPAPER=""

change_wallpaper() {
    while true; do
        RANDOM_WALLPAPER=$(find "$WALLPAPER_DIR" -type f | shuf -n 1)
        hyprctl hyprpaper preload "$RANDOM_WALLPAPER"
        hyprctl hyprpaper wallpaper "eDP-1,$RANDOM_WALLPAPER"
        sleep $INTERVAL
        hyprctl hyprpaper unload unused
    done
}

change_wallpaper

