$scripts = $HOME/.config/hypr/scripts

#hyprpm
#exec-once = hyprpm reload -n &

# Startup
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP --all &
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME &

# Services
exec-once = noctalia-shell &
exec-once = $scripts/theker

# Applications
exec-once = vivaldi-stable &
