#Gestures

        gesture = 2, pinchin, cursorZoom, 3.5
        gesture = 2, pinchout, cursorZoom, out, 3.5

        gesture = 3, up, dispatcher, exec, $scripts/volume --inc #NOTE: volume up
        gesture = 3, down, dispatcher, exec, $scripts/volume --dec #NOTE: volume down
        gesture = 3, horizontal, workspace

        gesture = 4, up, fullscreen
        gesture = 4, down, close
        gesture = 4, right, move
        gesture = 4, left, move
