vim.pack.add({
	"https://github.com/MeanderingProgrammer/render-markdown.nvim",
	"https://github.com/nvim-mini/mini.icons",
})

require("render-markdown").setup({
	render_modes = { "n", "no", "c", "t", "i", "ic" },
	heading = {
		enabled = true,
		sign = true,
		-- icons = { -- position = right
		-- 	"",
		-- 	"",
		-- 	"",
		-- 	"",
		-- 	"",
		-- 	"",
		-- },
		icons = { "󰼏 ", "󰼐 ", "󰼑 ", "󰼒 ", "󰼓 ", "󰼔 ", "󰼕 ", "󰼖 ", "󰼗 ", "󰿪 " },
		position = "inline",
		signs = { "󱅿 " },
		width = "block",
		left_pad = 0,
		right_pad = 1,
		border = false,
		above = "",
		below = "",
		-- backgrounds = {
		-- 	"MiniStatusLineModeNormal",
		-- 	"MiniStatusLineModeInsert",
		-- 	"MiniStatusLineModeReplace",
		-- 	"MiniStatusLineModeVisual",
		-- 	"MiniStatusLineModeCommand",
		-- 	"MiniStatusLineModeOther",
		-- },
	},
	code = {
		enabled = true,
		sign = true,
		conceal_delimiters = true,
		language = true,
		position = "right",
		language_icon = true,
		language_name = true,
		language_info = true,
		disable_background = { "diff" },
		width = "block",
		min_width = 0,
		border = "thin",
		language_border = "▁",
		left_pad = 1,
		right_pad = 1,
		language_left = "█",
		language_right = "█",
		above = "▁",
		below = "▔",
		inline = true,
		style = "full",
	},
	bullet = {
		icons = { "●", "", "◆", "◇", "", "" },
	},
	checkbox = {
		enabled = true,
		unchecked = {
			icon = "󰄱 ",
		},
		checked = {
			icon = "󰱒 ",
		},
		custom = {
			todo = { raw = "[-]", rendered = "", highlight = "RenderMarkdownTodo", scope_highlight = nil },
		},
	},

	indent = { enabled = true },
	latex = { enabled = false },
	html = { enabled = true },
	yaml = { enabled = true },
})
