#!/usr/bin/env bash

# Style
dir="$HOME/.config/rofi/launchers/"
theme='style'

# Define menu items as "Label|Function Name"
MENU_ITEMS=(
)

# Define functions for each menu item

# Create Rofi menu
CHOICE=$(for item in "${MENU_ITEMS[@]}"; do
    IFS="|" read -r label _ <<<"$item"
    echo "$label"
done | rofi -dmenu -p "Title" -theme ${dir}/${theme}.rasi)

# Match selection and call corresponding function
for item in "${MENU_ITEMS[@]}"; do
    IFS="|" read -r label func <<<"$item"
    if [[ "$CHOICE" == "$label" ]]; then
        "$func"
        exit 0
    fi
done

exit 1
